" bundle
source $HOME/dotfiles/vimrc.bundle
" basic
source $HOME/dotfiles/vimrc.basic
" keymap
source $HOME/dotfiles/vimrc.keymap
" plugins
source $HOME/dotfiles/vimrc.plugins
" taglist
source $HOME/dotfiles/vimrc.taglist
" memolist
source $HOME/dotfiles/vimrc.memolist
" js
source $HOME/dotfiles/vimrc.js
