" $HOME/dotfiles/vimrc.bundle
source $HOME/dotfiles/vimrc.bundle
" $HOME/dotfiles/vimrc.basic
source $HOME/dotfiles/vimrc.basic
" $HOME/dotfiles/vimrc.keymap
source $HOME/dotfiles/vimrc.keymap
" $HOME/dotfiles/vimrc.plugins
source $HOME/dotfiles/vimrc.plugins
" $HOME/dotfiles/vimrc.taglist
source $HOME/dotfiles/vimrc.taglist
" $HOME/dotfiles/vimrc.memolist
source $HOME/dotfiles/vimrc.memolist
" $HOME/dotfiles/vimrc.js
source $HOME/dotfiles/vimrc.js
